// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Wire/greetings"
)

// Injectors from wire.go:

func InitializeEvent() greetings.Event {
	message := greetings.NewMessage()
	greeter := greetings.NewGreeter(message)
	event := greetings.NewEvent(greeter)
	return event
}
